# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pandar_msgs/PandarGps.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PandarGps(genpy.Message):
  _md5sum = "a075038e2dd27f000f34f827c3e40eec"
  _type = "pandar_msgs/PandarGps"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
uint32 used
uint16 year
uint16 month
uint16 day
uint16 hour
uint16 minute
uint16 second
uint32 fineTime
uint32 flag"""
  __slots__ = ['stamp','used','year','month','day','hour','minute','second','fineTime','flag']
  _slot_types = ['time','uint32','uint16','uint16','uint16','uint16','uint16','uint16','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,used,year,month,day,hour,minute,second,fineTime,flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PandarGps, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.used is None:
        self.used = 0
      if self.year is None:
        self.year = 0
      if self.month is None:
        self.month = 0
      if self.day is None:
        self.day = 0
      if self.hour is None:
        self.hour = 0
      if self.minute is None:
        self.minute = 0
      if self.second is None:
        self.second = 0
      if self.fineTime is None:
        self.fineTime = 0
      if self.flag is None:
        self.flag = 0
    else:
      self.stamp = genpy.Time()
      self.used = 0
      self.year = 0
      self.month = 0
      self.day = 0
      self.hour = 0
      self.minute = 0
      self.second = 0
      self.fineTime = 0
      self.flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I6H2I().pack(_x.stamp.secs, _x.stamp.nsecs, _x.used, _x.year, _x.month, _x.day, _x.hour, _x.minute, _x.second, _x.fineTime, _x.flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.stamp.secs, _x.stamp.nsecs, _x.used, _x.year, _x.month, _x.day, _x.hour, _x.minute, _x.second, _x.fineTime, _x.flag,) = _get_struct_3I6H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I6H2I().pack(_x.stamp.secs, _x.stamp.nsecs, _x.used, _x.year, _x.month, _x.day, _x.hour, _x.minute, _x.second, _x.fineTime, _x.flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.stamp.secs, _x.stamp.nsecs, _x.used, _x.year, _x.month, _x.day, _x.hour, _x.minute, _x.second, _x.fineTime, _x.flag,) = _get_struct_3I6H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I6H2I = None
def _get_struct_3I6H2I():
    global _struct_3I6H2I
    if _struct_3I6H2I is None:
        _struct_3I6H2I = struct.Struct("<3I6H2I")
    return _struct_3I6H2I
